#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


#bspc monitor -d    󰊢   󱏒 󰃇
bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width        2
bspc config window_gap          8

bspc config split_ratio          0.5

# Set the default layout to grid
#bspc config automatic_scheme spiral
bspc config initial_polarity second_child
bspc config borderless_monocle true
bspc config gapless_monocle true
#bspc config single_monocle true


#Autostart Apllication
# Start of Selection
nitrogen --restore &
dunst &
polybar &
xbindkeys &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
picom --config ~/.config/picom/picom.conf &
libinput-gestures-setup start &

#### BSPWM coloring ####
bspc config normal_border_color "#4c566a" 
bspc config active_border_color "#ffffff" 
bspc config focused_border_color "#ffffff" 
bspc config presel_feedback_color "#ffffff" 
bspc config urgent_border_color "#dd2727"
